---
intakes:
- name: Techno1
  protocol: tcp
  port: 20516
  intake_key: <IntakeKey1>
- name: Techno2
  input_protocol: tcp
  port: 20517
  protocol: http
  intake_key: <IntakeKey2>
- name: Forwarder
  stats: true 
  intake_key: <IntakeKey3>
